apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: revkelo/clustershpachatboteducativoespecializadoenmicrosoft365-frontend:latest
          ports:
            - containerPort: 4200
          resources:
            requests:
              cpu: "100m"
            limits:
              cpu: "250m"
